vim.cmd("syntax on")
vim.cmd(":set modifiable")
vim.cmd(":set number")
vim.cmd(":set cursorline")
vim.cmd(":set autoindent")
vim.cmd(":set smartindent")
vim.cmd(":set smarttab")
vim.cmd(":set linebreak")
vim.cmd(":set showmatch")
vim.cmd(":set showcmd")
vim.cmd(":set encoding=utf-8")
vim.cmd(":set fileencoding=utf-8")
vim.cmd(":set clipboard=unnamedplus")
vim.cmd(":set relativenumber")
vim.cmd(":set expandtab")
vim.cmd(":set tabstop=2")
vim.cmd(":set softtabstop=2")
vim.cmd(":set shiftwidth=2")
vim.cmd(":set hlsearch")
vim.cmd(":set mouse=a")
vim.cmd(":set mousemoveevent")
vim.cmd("filetype indent on")
vim.g.is_bash = 1
vim.g.loaded_perl_provider = 0
